version: "3.7"

services:
  redis:
    image: "redis/redis-stack"
    ports:
      - "6379:6379"
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ~/mount/postgres:/var/lib/postgresql/data